name: Run on Pull Request

on:
  pull_request:
    branches:
      - main

env:
  GODOT_VERSION: 4.2.1
  EXPORT_NAME: MasterOfElements
  PROJECT_PATH: .

jobs:
  export-windows:
    name: Windows Export
    runs-on: ubuntu-latest    
    steps:
      - name: Checkout
        uses: actions/checkout@v3.3.0
        with:
          lfs: true
      - name: install wine
        id: wine_install
        run: |
          sudo apt install wine64
          echo "WINE_PATH=$(which wine64)" >> $GITHUB_OUTPUT
      - name: export game
        id: export
        # Use latest version (see releases for all versions)
        uses: firebelley/godot-export@v5.2.1
        with:
          # Defining all the required inputs
          godot_executable_download_url: https://downloads.tuxfamily.org/godotengine/${GODOT_VERSION}/Godot_v${GODOT_VERSION}-stable_linux.x86_64.zip
          godot_export_templates_download_url: https://downloads.tuxfamily.org/godotengine/${GODOT_VERSION}/mono/Godot_v${GODOT_VERSION}-stable_mono_export_templates.tpz          
          relative_project_path: ${PROJECT_PATH}/
          archive_output: true
          cache: true
          wine_path: ${{ steps.wine_install.outputs.WINE_PATH }} # set the wine path here which is the output of the wine_install step
        run: |
          ls -la