name: Run on Pull Request

on:
  pull_request:
    branches:
      - main

jobs:
  export-windows:
    name: Windows Export
    runs-on: ubuntu-latest    
    steps:
      - name: Checkout
        uses: actions/checkout@latest
        with:
          fetch-depth: 0
          lfs: true
      - name: install wine
        id: wine_install
        run: |
          sudo apt install wine64
          echo "WINE_PATH=$(which wine64)" >> $GITHUB_OUTPUT
      - name: info
        id: info
        run: |
          printenv
          ls -la
      - name: export game
        id: export
        # Use latest version (see releases for all versions)
        uses: firebelley/godot-export@v5.2.1
        with:
          # Defining all the required inputs
          godot_executable_download_url: https://downloads.tuxfamily.org/godotengine/4.2.1/Godot_v4.2.1-stable_linux.x86_64.zip
          godot_export_templates_download_url: https://downloads.tuxfamily.org/godotengine/4.2.1/mono/Godot_v4.2.1-stable_mono_export_templates.tpz          
          relative_project_path: ./
          archive_output: true
          cache: true
          wine_path: ${{ steps.wine_install.outputs.WINE_PATH }} # set the wine path here which is the output of the wine_install step
      - uses: ncipollo/release-action@v1
        with:
          artifacts: ${{ steps.export.outputs.archive_directory }}/*          
          generateReleaseNotes: true
          name: pr-${{ github.ref_name }}
          tag: pr-${{ github.ref_name }}
          artefactErrorsFailBuild: true
          updateOnlyUnreleased: true
          allowUpdates: true
          prerelease: true
          makeLatest: false
          